### ISSUE TITLE
linstor -m returns wrong exit code when failure

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-client#10]
It always returns `0` (success)

**Comment by rp-** [comment]
well, this is on purpose. If you want to check on failure you need to evaluate the `ret_code` fields if they masked with error.

exit code would only be non zero if it couldn't create json output.

Also the client machine readable output from the client was a cheap way to give external program a way to somewhat parse the output and we tried to keep it stable as possible.
But for new scripts and other thinks we recommend to use the new REST API:
https://app.swaggerhub.com/apis-docs/Linstor/Linstor

**Comment by oneumyvakin** [comment]
Obviously it's an issue, there common approach of any exec() wrappers in programming languages is to interpret 0 as success and other exit code as error. So this architectural decision brakes common approach and UX.

**Comment by rck** [comment]
As none of the plugins uses `-m` anymore, IMO we should just snap it.

See, this also solves the problem of "friendly people" like @oneumyvakin . They can't complain about something you give them for free if it does not exist.

**Comment by oneumyvakin** [comment]
Maybe I've to perform additional efforts for handling such cases because I'm using Golang which is statically typed language and I've to perform decoding response twice first for checking for error and than for requested data.

**Comment by rck** [comment]
What has the command line client and it's json output to do with Go? If you use Go, you should use the client from [https://godoc.org/github.com/LINBIT/golinstor/client](golinstor). If this does not fulfill your needs, open an issue there. With a concrete example. With what happens at which call and why this isn't good enough for you. Then we will look into it and try to help you.

**Comment by kvaps** [comment]
It might be useful for someone, I'm using [this function](https://github.com/OpenNebula/addon-linstor_un/blob/b764b9d8209689de2f37a689125e29f1cf3f7ac7/datastore/linstor_un/linstor_utils.sh#L279-L289) for check linstor's ret_code on bash:
```bash
#-------------------------------------------------------------------------------
# Checking return code for linstor command
#   @param $1 - ret_code
#-------------------------------------------------------------------------------
linstor_error() {
  local RET_CODE="$(printf '0x%X\n' $1)"
  local MASK_ERROR="0xC000000000000000"

  # Bitwise AND
  [ $(printf '0x%X\n' "$(( "$RET_CODE" & "$MASK_ERROR" ))") == "$MASK_ERROR" ]
}
```

The rest masks can be found in [consts.json](https://github.com/LINBIT/linstor-common/blob/master/consts.json) file

**Comment by oneumyvakin** [comment]
@rck Yes, I know that REST-API is exist, but I've started with command-line interface because documentation describes CLI interface, not API.
For me it's just easier to walkthrough documentation to understand how to interact with system, because it's not so easy even with CLI examples.
When documentation will use API for describing how to interact with system I'll use API.

**Comment by rck** [comment]
Okay, I understand. I guess in the long run you should try to switch (and maybe help improving the godoc). Using Go to call a Python CLI and parsing back stuff is pretty ugly. Especially when there is a native Go library, but whatever works for you :).

FWIW, the cli client also uses the REST-API and has a `--curl` option. This can be useful to find the correct API endpoints/find the correct Go structs/required fields and endpoints.

**Comment by raltnoeder** [comment]
I am not sure what the linstor client's exit codes are, but I would expect that it exits with a nonzero exit code if the client failed (or e.g. communication with the controller failed), and exits with exit code zero if communication with the server was successful.

The server (LINSTOR controller) returns a datastructure that contains a list of responses, where each response may be a confirmation of success, a notice/info message, a warning or an error. All of those have identifiable (machine readable) error codes, a human readable text representation (a description section and optionally a cause, correction and details section) and a machine-readable map of referenced objects (e.g., describing the type of object and name of such an object that the error is related to).
Obviously this information can not be represented as a single exit code by the linstor client (not even the numerical error codes, because exit codes are limited to an 8 bit range, and LINSTOR has way more return codes), which is also the reason why applications should always at least interpret all the numerical return codes that LINSTOR returns to decide whether an operation was successful or not
(and in the ideal case, forward relevant information to the user through whatever frontend is available for that, e.g. a text message or a suitable graphical symbol on a monitoring GUI).

This design was chosen because the information provided by the traditional approach of using a single exit code where 0 means success and everything else means failure was deemed completely underpowered and inadequate for building a complex application like LINSTOR in such a way that it could be integrated with other software and still provide meaningful information on the status of requests.
