### ISSUE TITLE
Feature request: Get resources by aux-property, show all aux-properties

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-client#22]
The same way like kubectl is working with kubernetes labels:

Get all nodes with `Aux/cluster` set:
```
linstor node list -l cluster
```

Get all nodes with `Aux/cluster=1`
```
linstor node list -l cluster=1
```

Show all aux properties for all nodes:
```
linstor node list --show-aux-properties
```

**Comment by raltnoeder** [comment]
This could possibly be implemented as a filter to the list command on the client side, but will have roughly O(n*m) time and space complexity for n objects with m properties (like the list command if all properties are included), since object properties were not designed to serve as an index for looking up the objects they are associated with. Implementing it on the controller side would serve little purpose, since the disadvantages of doing that outweigh any advantages this would have.

**Comment by kvaps** [comment]
Anyway, this function would be quite usable for us, because we're separating our nodes through availability zones using aux-properties, it would be nice to list all the nodes in one availability zone

**Comment by kvaps** [comment]
BTW here is an example how to get at least somehow grepable output:

```bash
linstor -m n l | jq -rc '.[].nodes[] | "\(.name) \([ (.props[] | select(.key | contains("Aux"))) ] | from_entries)"'
```

example output:
```bash
m1c4 {"Aux/side":"a","Aux/moonshot":"1"}
m1c5 {"Aux/side":"a","Aux/moonshot":"1"}
m1c6 {"Aux/side":"a","Aux/hosting":"true","Aux/moonshot":"1"}
m1c7 {"Aux/side":"b","Aux/hosting":"true","Aux/moonshot":"1"}
m1c8 {"Aux/side":"b","Aux/hosting":"true","Aux/moonshot":"1"}
m1c9 {"Aux/side":"b","Aux/hosting":"true","Aux/moonshot":"1"}
```

**Comment by ddpolyakov** [comment]
This could be very useful in many production cases. Multi-DC, fault domains etc.

**Comment by frenzymind** [comment]
Yes, it would be nice to have this this feature!

**Comment by rp-** [comment]
`--props` and `--show-aux-properties` was added with release 1.7.0 and 1.1.0
