### ISSUE TITLE
Feature request: Ability to set multipath for resource group

### ISSUE THREAD

**Issue by fibd** [LINBIT/linstor-client#55]
According to documentation: https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-creating-multiple-drbd-paths
 its not possible to enable multipath directly for resource group, so all the resources spawned by it will have appropriate settings assigned.
It would be nice function to allow this kind of setting at resource group level so I dont need to assign path settings for each new resource, at the moment I need to add for each new resource path1 and path2 in all the node combinations.

**Comment by ghernadi** [comment]
Looks like we need to update our documentation, but since a few versions there is also a
``` 
$ linstor nc p c -h
usage: linstor node-connection path create [-h]
                                           node_a node_b path_name
                                           netinterface_a netinterface_b
...
```
command, which should also solve your problem. 
However, please keep in mind that if both, node-connection(s) as well as rsc-connection(s) exist, rsc-connections will be prioritized (i.e. in this case the existing node-connections will be ignored). 

We had a few issues though with this command, especially deleting node-connection paths was buggy, so make sure to use the latest Linstor version and let us know if you still find bugs.

If this does not solve your problem, feel free to re-open this issue.
